package no.nav.hjelpemidler.soknad.mottak.river

import com.fasterxml.jackson.databind.JsonNode
import io.github.oshai.kotlinlogging.KotlinLogging
import io.ktor.client.engine.apache.Apache
import no.nav.hjelpemidler.behovsmeldingsmodell.BehovsmeldingType
import no.nav.hjelpemidler.configuration.Environment
import no.nav.hjelpemidler.http.slack.slack
import no.nav.hjelpemidler.http.slack.slackIconEmoji
import no.nav.hjelpemidler.serialization.jackson.value
import no.nav.hjelpemidler.soknad.mottak.client.GrunndataClient

object AutoGenerateDocumentTitle {
    private const val GRENSE_FOR_LANG_DOKUMENTBESKRIVELSE = 150

    private val log = KotlinLogging.logger {}
    private val slackClient by lazy { slack(engine = Apache.create()) }

    private val environment = Environment.current.toString()

    suspend fun generateTitle(behovsmelding: JsonNode): String {
        val behovsmeldingType: BehovsmeldingType =
            behovsmelding["behovsmeldingType"]?.value() ?: BehovsmeldingType.SØKNAD

        if (Environment.current.isLocal) {
            return defaultTitle(behovsmeldingType)
        }

        val hmsnrs = when (behovsmeldingType) {
            BehovsmeldingType.BRUKERPASSBYTTE -> setOf(behovsmelding["brukerpassbytte"]["hjelpemiddel"]["artnr"].textValue())
            else -> {
                val hmHmsnrs = behovsmelding["soknad"]["hjelpemidler"]["hjelpemiddelListe"]
                    .mapNotNull { it["hmsNr"].asText() }
                    .filter { it.isNotEmpty() }.toSet()

                val tilbehørListe = behovsmelding["soknad"]["hjelpemidler"]["tilbehørListe"]
                val tilbehørHmsnrs =
                    tilbehørListe?.mapNotNull { it["hmsnr"].asText() }?.filter { it.isNotEmpty() }?.toSet() ?: emptyList()

                hmHmsnrs + tilbehørHmsnrs
            }
        }

        return generateTitle(hmsnrs, behovsmeldingType)
    }

    private suspend fun generateTitle(hmsnrs: Set<String>, behovsmeldingType: BehovsmeldingType): String {
        val produkter = try {
            GrunndataClient.hentProdukter(hmsnrs)
        } catch (e: Exception) {
            log.warn(e) { "Kunne ikke utlede tittel for hmsnrs: $hmsnrs, behovsmeldingType: $behovsmeldingType" }
            postToSlack(hmsnrs)
            return defaultTitle(behovsmeldingType)
        }

        val titlerForHjelpemidler = produkter
            .filter { it.main }
            .asSequence()
            .mapNotNull {it.isoCategoryTitleShort}
            .filter { it.isNotEmpty() }
            .toSet()
            .sorted()
            .joinToString(separator = ", ")
            .lowercase()

        val titlerForTilbehør = produkter
            .filter { it.accessory }
            .asSequence()
            .mapNotNull {
                val tilbehørTittel = ISO4_TITLER[it.isoCategory.take(4)]
                if (tilbehørTittel.isNullOrBlank()) {
                    log.error{"Mangler 4-sifret mapping for isokode ${it.isoCategory} for hmsnr ${it.hmsArtNr}, den bør legges til"}
                }
                tilbehørTittel
            }
            .map { "tilbehør ${it}" }
            .filter { it.isNotEmpty() }
            .toSet()
            .sorted()
            .joinToString(separator = ", ")
            .lowercase()

        val title = listOf(titlerForHjelpemidler, titlerForTilbehør).filter { it.isNotEmpty() }.joinToString(", ")

        if (title.isEmpty()) {
            log.warn { "Kunne ikke utlede tittel for hmsnrs: $hmsnrs, behovsmeldingType: $behovsmeldingType" }
            postToSlack(hmsnrs)
            return defaultTitle(behovsmeldingType)
        }

        postToSlack(title)

        return when (behovsmeldingType) {
            BehovsmeldingType.BESTILLING -> "Bestilling av: $title"
            BehovsmeldingType.SØKNAD -> "Søknad om: $title"
            BehovsmeldingType.BYTTE, BehovsmeldingType.BRUKERPASSBYTTE -> "Bytte av: $title"
        }
    }

    private fun defaultTitle(behovsmeldingType: BehovsmeldingType) =
        when (behovsmeldingType) {
            BehovsmeldingType.BESTILLING -> "Bestilling av hjelpemidler"
            BehovsmeldingType.SØKNAD -> "Søknad om hjelpemidler"
            BehovsmeldingType.BYTTE, BehovsmeldingType.BRUKERPASSBYTTE -> "Bytte av hjelpemidler"
        }

    private suspend fun postToSlack(title: String) {
        if (!Environment.current.isProd || title.length <= GRENSE_FOR_LANG_DOKUMENTBESKRIVELSE) return
        try {
            slackClient.sendMessage(
                username = "hm-soknadsbehandling",
                icon = slackIconEmoji(":this-is-fine-fire:"),
                channel = "#digihot-brukers-hjelpemiddelside-dev",
                message = "$environment - Dokumentbeskrivelsen ble over $GRENSE_FOR_LANG_DOKUMENTBESKRIVELSE tegn: '$title'"
            )
        } catch (e: Exception) {
            log.warn(e) { "Posting av dokumentbeskrivelse til Slack feilet" }
        }
    }

    private suspend fun postToSlack(hmsnrs: Set<String>) {
        if (!Environment.current.isProd) return
        try {
            slackClient.sendMessage(
                username = "hm-soknadsbehandling",
                icon = slackIconEmoji(":this-is-fine-fire:"),
                channel = "#digihot-brukers-hjelpemiddelside-dev",
                message = "$environment - Mangelfull dokumentbeskrivelse for følgende hjelpemidler: ${hmsnrs.joinToString()}",
            )
        } catch (e: Exception) {
            log.warn(e) { "Posting av melding om mangelfull dokumentbeskrivelse til Slack feilet" }
        }
    }
}
