apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-soknadsbehandling
    team: teamdigihot
  name: hm-soknadsbehandling
  namespace: teamdigihot
spec:
  image: {{ image }}
  team: teamdigihot
  liveness:
    path: /isalive
  readiness:
    path: /isready
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 4
  accessPolicy:
    outbound:
      rules:
        - application: hm-soknadsbehandling-db
  azure:
    application:
      enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  env:
    - name: SOKNADSBEHANDLING_DB_BASEURL
      value: http://hm-soknadsbehandling-db.teamdigihot.svc.cluster.local/api

