apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-soknadsbehandling
    team: teamdigihot
  name: hm-soknadsbehandling
  namespace: teamdigihot
spec:
  image: {{ image }}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 4
  accessPolicy:
    outbound:
      rules:
        - application: hm-soknadsbehandling-db
        - application: hm-grunndata-search
        - application: digihot-oppslag
        - application: hm-delbestilling-api
      external:
        - host: hm-infotrygd-proxy.prod-fss-pub.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
        - host: hooks.slack.com
  azure:
    application:
      enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  envFrom:
    - secret: hm-influxdb-secret
    - secret: hm-soknadsbehandling
  env:
    - name: SOKNADSBEHANDLING_DB_BASEURL
      value: http://hm-soknadsbehandling-db.teamdigihot.svc.cluster.local/api
    - name: DELBESTILLING_API_BASEURL
      value: http://hm-delbestilling-api.teamdigihot.svc.cluster.local/api

