CREATE TABLE IF NOT EXISTS V1_JOURNAL_POST
(
    FNR                 CHAR(11)                 NOT NULL,
    AKTOER_ID           VARCHAR(20)              NOT NULL,
    JOURNALPOST_ID      VARCHAR(12)              NOT NULL,
    FAGSAK_ID           VARCHAR(12)              ,
    BEHANDLENDE_ENHET   VARCHAR(8)               NOT NULL,
    DATO_REGISTRERT     DATE                     ,
    PRIMARY KEY (FNR, AKTOER_ID, JOURNALPOST_ID) ,
    created             TIMESTAMP WITH TIME ZONE NOT NULL default (now() at time zone 'utc')
);

CREATE INDEX V1_JOURNAL_POST_FNR_IDX ON V1_JOURNAL_POST (FNR);
CREATE INDEX V1_JOURNAL_POST_AKTOER_ID_IDX ON V1_JOURNAL_POST (AKTOER_ID);
CREATE INDEX V1_JOURNAL_POST_JOURNALPOST_ID_IDX ON V1_JOURNAL_POST (JOURNALPOST_ID);

CREATE TABLE IF NOT EXISTS V1_SOKNAD
(
    FNR             CHAR(11)        NOT NULL,
    BEHANDLINGS_ID  VARCHAR(20)     NOT NULL,
    DATA            JSONB           NOT NULL,
    PRIMARY KEY (FNR, BEHANDLINGS_ID),
    created   TIMESTAMP WITH TIME ZONE NOT NULL default (now() at time zone 'utc')
);

CREATE INDEX V1_SOKNAD_FNR_IDX ON V1_SOKNAD (FNR);
CREATE INDEX V1_SOKNAD_BEHANDLINGS_ID_IDX ON V1_SOKNAD (BEHANDLINGS_ID);