CREATE TABLE IF NOT EXISTS V1_SOKNAD
(
    FNR       CHAR(11)                 NOT NULL,
    SOKNADS_ID VARCHAR(20)              NOT NULL,
    DATA      JSONB                    NOT NULL,
    PRIMARY KEY (FNR, SOKNADS_ID),
    created   TIMESTAMP WITH TIME ZONE NOT NULL default (now() at time zone 'utc')
);

CREATE INDEX V1_SOKNAD_FNR_IDX ON V1_SOKNAD (FNR);
CREATE INDEX V1_SOKNAD_SOKNADS_ID_IDX ON V1_SOKNAD (SOKNADS_ID);
