CREATE TABLE IF NOT EXISTS V1_SOKNAD_AUTOMATISK_BEHANDLING
(
    SOKNAD_ID      CHAR(26)                 NOT NULL,
    FNR            CHAR(11)                 NOT NULL,
    AKTOER_ID      VARCHAR(20)              NOT NULL,
    BEHANDLINGS_ID VARCHAR(20)              NOT NULL,
    PRIMARY KEY (FNR, BEHANDLINGS_ID),
    created        TIMESTAMP WITH TIME ZONE NOT NULL default (now() at time zone 'utc')
);

CREATE INDEX V1_SOKNAD_AUTOMATISK_BEHANDLING_SOKNAD_ID_IDX ON V1_SOKNAD_AUTOMATISK_BEHANDLING (SOKNAD_ID);