CREATE TABLE IF NOT EXISTS V2_SOKNAD_AUTOMATISK_BEHANDLING
(
    ID        CHAR(26)                 NOT NULL,
    FNR       CHAR(11)                 NOT NULL,
    AKTOER_ID VARCHAR(20)              NOT NULL,
    SOKNADS_ID VARCHAR(20)              NOT NULL,
    PRIMARY KEY (FNR, SOKNADS_ID),
    created   TIMESTAMP WITH TIME ZONE NOT NULL default (now() at time zone 'utc')
);

CREATE INDEX V2_SOKNAD_AUTOMATISK_BEHANDLING_ID_IDX ON V2_SOKNAD_AUTOMATISK_BEHANDLING (ID);

CREATE TABLE IF NOT EXISTS V2_SOKNAD
(
    FNR       CHAR(11)                 NOT NULL,
    SOKNADS_ID VARCHAR(20)              NOT NULL,
    DATA      JSONB                    NOT NULL,
    PRIMARY KEY (FNR, SOKNADS_ID),
    created   TIMESTAMP WITH TIME ZONE NOT NULL default (now() at time zone 'utc')
);

CREATE INDEX V2_SOKNAD_FNR_IDX ON V2_SOKNAD (FNR);
CREATE INDEX V2_SOKNAD_SOKNADS_ID_IDX ON V2_SOKNAD (SOKNADS_ID);