DROP TABLE IF EXISTS V1_SOKNAD;
DROP INDEX IF EXISTS V1_SOKNAD_FNR_IDX;
DROP INDEX IF EXISTS V1_SOKNAD_BEHANDLINGS_ID_IDX;

DROP TABLE IF EXISTS V1_SOKNAD_AUTOMATISK_BEHANDLING;
DROP INDEX IF EXISTS V1_SOKNAD_AUTOMATISK_BEHANDLING_SOKNAD_ID_IDX;