package no.nav.hjelpemidler.soknad.mottak.service

enum class Status {
    VENTER_GODKJENNING, GODKJENT_MED_FULLMAKT, INNSENDT_FULLMAKT_IKKE_PÅKREVD, BRUKERPASSBYTTE_INNSENDT, GODKJENT, SLETTET, UTLØPT, ENDELIG_JOURNALFØRT, BESTILLING_FERDIGSTILT, BESTILLING_AVVIST,
    VEDTAKSRESULTAT_INNVILGET, VEDTAKSRESULTAT_MUNTLIG_INNVILGET, VEDTAKSRESULTAT_DELVIS_INNVILGET, VEDTAKSRESULTAT_AVSLÅTT, VEDTAKSRESULTAT_ANNET, UTSENDING_STARTET, VEDTAKSRESULTAT_HENLAGTBORTFALT;
}
