name: Deploy to prod

on:
  release:
    types:
      - published

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    permissions:
      contents: "write"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4
      - uses: nais/login@v0
        name: Nais-login
        id: nais-login
        with:
          team: teamdigihot
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - name: Define IMAGE
        env:
          VERSION_TAG: ${{ github.event.release.tag_name }}
          REGISTRY: ${{ steps.nais-login.outputs.registry }}
          APP: ${{ github.event.repository.name }}
        run: |
          IMAGE=$REGISTRY/$APP:$VERSION_TAG
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV
          echo $IMAGE
      - uses: nais/deploy/actions/deploy@v1
        name: Deploy to prod-gcp
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/nais-prod.yaml,nais/alerts.yaml
      - name: Post-production
        uses: navikt/digihot-deploy/actions/post-production@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
