name: Vulnerabilities scanning of dependencies
on: [push]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/gradle-jdk12@main
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: monitor
        args: --configuration-attributes=usage:java-runtime --project-name=${{ github.repository }} --remote-repo-url=https://github.com/${{ github.repository }}.git --org=hjelpemiddelbehov
